import { useState } from "react";
import { Link } from "react-router-dom";


const Faq = () => {
    const faqs = [
        {
          id: 1,
          question: "How are payments made?",
          answer: "Your commission will be automatically transferred to your Affiliate account every Tuesday, but only if the amount exceeds 30 USD, which is the minimum amount for withdrawal."
        },
        {
          id: 2,
          question: "How much can I earn?",
          answer: "There is no answer to that question - it all depends on your efforts. Many of our Affiliates make tens of thousands of dollars a month."
        },
        {
          id: 3,
          question: "Why is my earning balance negative?",
          answer: "Sometimes players win, and therefore under the revenue share model, both the Affiliate and the betting company bear losses. Negative balances are offset by the revenue earned from the losses of other players, so to be in the black you need to increase the number of converted customers."
        },
        {
          id: 4,
          question: "What are the affiliate programs model?",
          answer: [
            "Our affiliate payment models include:",
            "1. RevShare - You will receive 25% of the revenue generated by the betting company as a standard." ,
            "2. CPA - A fixed rate is paid for each player who completes specified actions.", 
            "3. Referral System - Affiliates can earn additional revenue from other affiliates they recruit. If an affiliate refers another affiliate (sub-affiliate)  they receive a 3% commission on the sub-affiliate's total profit."
          ]
        }
      ];
    const [openId,setOpenId]= useState(false)
    return (
        <div className="py-4">
           <div className="py-4">
        <div className=" md:skew-x-[30deg] lg:skew-x-[30deg]  mx-auto  w-full md:w-min lg:w-min px-[10%] bg-black  py-2">
        <h3 className="transform md:skew-x-[-30deg] lg:skew-x-[-30deg]  md:text-3xl text-center lg:text-5xl text-3xl text-commonYellow  py-2 whitespace-nowrap font-bold">
          FAQ
        </h3>
      </div>
        </div>

        <div className="py-4">
      <div className="mx-auto w-full max-w-5xl">
        {faqs.map((faq) => (
          <div key={faq.id} className="px-2  overflow-hidden my-[2px]">
            <button
              onClick={() => setOpenId(openId === faq.id ? null : faq.id)}
              className="w-full flex items-center gap-2 px-4 py-[3%] bg-black justify-between md:text-xl lg:text-3xl rounded-lg font-medium text-white"
            >
              <h3 className="mx-auto">{faq.question}</h3>
              <svg
                className={`h-5 w-5 transition-all font-bold duration-1000 ease-in-out ${
                  openId === faq.id ? "rotate-180" : "rotate-0"
                }`}
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                strokeWidth={2}
              >
                <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
              </svg>
            </button>
            {openId === faq.id && (
              <div className="p-4 my-1 bg-black opacity-90 max-h-48 overflow-y-auto">
                {Array.isArray(faq.answer) ? (
                   <p className="text-white text-sm leading-tight md:leading-tight lg:leading-relaxed">
                   {faq.answer.map((line, index) => (
                     <span key={index}>
                       {line}
                       <br />
                     </span>
                   ))}
                 </p>
                ) : (
                  <p className="text-white text-sm leading-tight md:leading-tight lg:leading-relaxed">{faq.answer}</p>
                )}
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
    <div className="flex flex-col items-center space-y-8 py-8 justify-center">
        <h3 className="text-2xl md:text-3xl lg:text-5xl font-bold">CONNECT AND EARN</h3>
        <Link to='/registration'>
        <button className="bg-black text-white hover:text-black text-center text-xl lg:text-2xl hover:bg-white px-12 py-4">
                    GET STARTED
                </button>
        </Link>
        
    </div>

        </div>
    );
};

export default Faq;